# Generated by Django 2.1.8 on 2019-04-09 00:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_auto_20190405_0110")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.recipe_image_file_path
            ),
        )
    ]
